### ISSUE TITLE
download button not appearing

### ISSUE THREAD

**Issue by dusk23342** [bradlys/monochromatic-panda#14]
trying to download youtube videos of really anything and the status bar isn't showing.

this is what the console showed:

googleads.g.doubleclick.net/pagead/id Failed to load resource: net::ERR_BLOCKED_BY_CLIENT
watch?v=wRBKYiumhQI:136 <link rel=preload> must have a valid `as` value
jquery.js:4 [Deprecation] /deep/ combinator is no longer supported in CSS dynamic profile. It is now effectively no-op, acting as if it were a descendant combinator. You should consider to remove it. See https://www.chromestatus.com/features/4964279606312960 for more details.
(anonymous) @ jquery.js:4
watch?v=wRBKYiumhQI:1 The resource https://r2---sn-jpocxaa-j8bl.googlevideo.com/generate_204?conn2 was preloaded using link preload but not used within a few seconds from the window's load event. Please make sure it wasn't preloaded for nothing.
watch?v=wRBKYiumhQI:1 The resource https://r2---sn-jpocxaa-j8bl.googlevideo.com/generate_204 was preloaded using link preload but not used within a few seconds from the window's load event. Please make sure it wasn't preloaded for nothing.
www.google.com/pagead/lvz?evtid=AP6Vqb9wby1wmLla2QMl3pFFC0_u6jhQX2JkV__RMvncS-9e61K1eTepnd65r1bQ736s9gQiYb7sp8stksQDEyIK5LuQ_jT_qQ&req_ts=1504497874&pg=watch&sigh=AP-8cyQRJ8GG9MexDpiCq1Y434aNE_kYgg Failed to load resource: net::ERR_BLOCKED_BY_CLIENT
static.doubleclick.net/instream/ad_status.js Failed to load resource: net::ERR_BLOCKED_BY_CLIENT
googleads.g.doubleclick.net/pagead/id Failed to load resource: net::ERR_BLOCKED_BY_CLIENT
www-pagead-id.js:105 GET https://googleads.g.doubleclick.net/pagead/id net::ERR_BLOCKED_BY_CLIENT
fb @ www-pagead-id.js:105
eb @ www-pagead-id.js:96
(anonymous) @ www-pagead-id.js:109
M @ www-pagead-id.js:52
kb @ www-pagead-id.js:106
(anonymous) @ www-pagead-id.js:122
ytplayer.config.assets.js
"/yts/jsbin/player-en_US-vfleWWlqf/base.js"

**Comment by bradlys** [comment]
Yeah. I'm on it. I have a fix coming. I have gotten it to work within the last couple hours. I just need to make it look decent because the UI is now different.

**Comment by 0joshuaolson1** [comment]
Another user wishing you success.
