### ISSUE TITLE
No download button

### ISSUE THREAD

**Issue by merrickw** [bradlys/monochromatic-panda#17]
Hi Bradly - I can't get the download button (or link) to appear for this:
https://www.youtube.com/watch?v=cMTAUr3Nm6I

I tried using the console as recommended to report an issue, but that command didn't work;

Any thoughts?

Thanks,
MW

**Comment by bradlys** [comment]
Yep. Doesn't show up for me either. I'll check it out! Thanks.

**Comment by merrickw** [comment]
Important song according to my 6 year old daughter!


-------- Original message --------

**Comment by bradlys** [comment]
Checking it now... Seems YouTube changed up some stuff. This might take a *little* longer than I expected. I'll try to fix this soon. It will be a bit more complicated.

**Comment by bradlys** [comment]
Should be resolved with latest update. Tried it and it worked. Sorry for the delay!

**Comment by merrickw** [comment]
Hi Bradly - I am seeing some pages where the download button disappears;
Also, I see cases where the download button is left from a previous page and operates on the previous video, not the current video.

Here's an example where no button (or link) appears:
https://www.youtube.com/watch?time_continue=2&v=l5HwNctJJsY

Regards,
Merrick
