### ISSUE TITLE
alternative format command is disabled  

### ISSUE THREAD

**Issue by asherbeny3** [bradlys/monochromatic-panda#4]
hi Bradlys ,

i notice in your video that ,the "alternative format" command from dropdown menu is active and showing other formats , but in my case is not active , it's disabled  

thank you 
best regards 
Ahmed

**Comment by bradlys** [comment]
Alrighty. Can you follow the steps I show in this video for error reporting? https://youtu.be/wRBKYiumhQI?t=2m50s

Thanks.
