### ISSUE TITLE
Cannot Able to Download Audio.

### ISSUE THREAD

**Issue by sanjaypradeep** [bradlys/monochromatic-panda#8]
Hi Bradly,

Good to have your app in chrome extension. But I couldn't able to download the audio.

What I did ?
Extension Added
Selected my fav video
clicked download (went to experimental - last option)
clicked audio format. But cannot able to download the audio.

**Comment by bradlys** [comment]
Can you give me the link to a video that's not working for you? I tested a video and it seemed to work for me.

The way to download those alternative formats (they're streaming formats) is usually by having them open in a new tab and then using ctrl+s to save the file. You can also right click on the links and do save link as. If that doesn't work, let me know.

**Comment by sanjaypradeep** [comment]
Thanks for helping me! Yep as you said, it's opening in a new tab, did ctrl+s. I can able to save it.
