### ISSUE TITLE
Some links don't start a download but open the video.

### ISSUE THREAD

**Issue by mar04** [bradlys/monochromatic-panda#9]
Hi,
went to https://www.youtube.com/watch?v=L0MK7qz13bU and selected 1280x720 mp4 and it starts a download, but selecting 640x360 either mp4 or webm just opens the video in what I think is a native chromium video player. From console:
```
Resource interpreted as Document but transferred with MIME type video/webm: "https://r7---sn-u2oxu-ajwe.googlevideo.com/videoplayback?source=youtube&upn…tle=FROZEN%20-%20Let%20It%20Go%20Sing-along%20%7C%20Official%20Disney%20HD".
Navigated to https://r7---sn-u2oxu-ajwe.googlevideo.com/videoplayback?source=youtube&upn…tle=FROZEN%20-%20Let%20It%20Go%20Sing-along%20%7C%20Official%20Disney%20HD
```

I'm using Chromium Version 56.0.2924.87 (64-bit) on Linux if that matters.

**Comment by bradlys** [comment]
I've come up with a solution. I'll be implementing and testing a fix shortly.

Involves the download attribute that is available within Chrome for <a> elements.

YouTube has changed things up recently.

**Comment by bradlys** [comment]
Tried my solution. Isn't working. YouTube is forcing the video name of 'videoplayback' when downloading the file. I cannot seem to override this.... Will be continuing to research.  Sorry for the annoyance. Save As seems to be your friend currently.

**Comment by mar04** [comment]
It's a bit inconvenient, but it's still the best chrome extension for this purpose that I was able to find, so thanks anyway.

**Comment by bradlys** [comment]
Resolved on my side. However, please note that if this happens again, Save As may be the only way to go. There are some things that YouTube can do on its side to force certain user interactions to occur and not even a plugin can solve that. Best of luck! @mar04
